import React, { useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import "./DynamicPage.css";
import axios from "axios";

function DynamicPage() {
  const [submitted, setSubmitted] = useState(false);
  const [inputValue, setInputValue] = useState("");
  const [displayedPrompt, setDisplayedPrompt] = useState("");
  const [images, setImages] = useState({ basicGan: "", dfGan: "", externalApi: "" }); // Add externalApi image state
  const contentRef = useRef(null);
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (inputValue.trim()) {
      setSubmitted(false);
      setDisplayedPrompt(inputValue);
      setTimeout(async () => {
        setSubmitted(true);
        await fetchGeneratedImages(inputValue); // Fetch generated images after submission
        contentRef.current?.scrollIntoView({ behavior: "smooth" });
      }, 100);
    }
  };

  const fetchGeneratedImages = async (prompt) => {
    try {
      const response = await axios.post("http://localhost:5000/generate", {
        text: prompt,
      });
      const { basic_generator_image, dfgan_generator_image, external_api_image } = response.data;

      setImages({
        basicGan: `data:image/png;base64,${basic_generator_image}`,
        dfGan: `data:image/png;base64,${dfgan_generator_image}`,
        externalApi: `data:image/jpeg;base64,${external_api_image}`, // Assuming the external API image is JPEG
      });

    } catch (error) {
      console.error("Error fetching generated images:", error);
    }
  };

  const navigateToHome = () => {
    navigate("/");
  };

  return (
    <div className="page-container">
      <div className="top-heading">
        <h1 onClick={navigateToHome}>PixPrompt</h1>
      </div>

      <div className="input-section">
        <h1>Text-to-Image Synthesis</h1>
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="Enter a prompt..."
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            required
          />
          <button type="submit">Submit</button>
        </form>
      </div>

      {submitted && (
        <div className="content-section" ref={contentRef}>
          <h2>Images Generated for: "{displayedPrompt}"</h2>
          <div className="image-row">
            <div className="image-block">
              <img
                src={images.basicGan || "https://via.placeholder.com/300"}
                alt="Basic Generator"
                className="image"
              />
              <p className="image-description">IMAGE GENERATED BY BASIC GENERATOR</p>
              {/* Display the FID score for Basic Generator */}
              <p>FID Score: 20.76</p>
            </div>
            <div className="image-block">
              <img
                src={images.dfGan || "https://via.placeholder.com/300"}
                alt="DFGAN Generator"
                className="image"
              />
              <p className="image-description">IMAGE GENERATED BY DF GAN</p>
              {/* Display the FID score for DFGAN Generator */}
              <p>FID Score: 3.95</p>
            </div>
            {/* Display the External API Image */}
            <div className="image-block">
              <img
                src={images.externalApi || "https://via.placeholder.com/300"}
                alt="External API Image"
                className="image"
              />
              <p className="image-description">IMAGE GENERATED BY EXTERNAL API</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default DynamicPage;
